### ISSUE TITLE
OpenCV in the resources

### ISSUE THREAD

**Issue by oscarlvp** [BastienAM/FaceReco#1]
Right now, the path to OpenCV is relative with respect to the source code of the project.

https://github.com/BastienAM/FaceReco/blob/master/src/main/java/Group1/FaceReco/FaceRecoApplication.java#L16

This is bad for the portability of the application. A way to overcome this could be to add the library to the resources. This way, the library will be added when the project is packed.
Also this changes the path to load the DLL.

**Comment by BastienAM** [comment]
Fixed ! df500ec

**Comment by oscarlvp** [comment]
Another thing to consider is to provide more meaningful messages when the the library and the rest of the folders can not be loaded or found.
